<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NextButton_Obj</name>
   <tag></tag>
   <elementGuidId>2eb751b5-38fa-4314-835f-291c591b7a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@src,&quot;buttonActionbarNext.gif&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@src,&quot;buttonActionbarNext.gif&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
